# Generated by Django 3.2.9 on 2021-11-11 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='shuttle',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='space_station',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='MedicalExamination',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Shuttle',
        ),
        migrations.DeleteModel(
            name='SpaceStation',
        ),
    ]
